# Generated by Django 5.2.3 on 2025-06-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandleJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('timestamp', models.DateField()),
                ('data', models.JSONField()),
            ],
            options={
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
    ]
